Add a blog post about why retargeting is bad
readthedocs/ethicalads.io pull request #109
Opened 2021-03-05 18:55 UTC by ericholscher

2021-03-05 22:52 UTC, davidfischer requested changes
I think this blog needs a bit of rework. It isn't really critiquing retargeting as much as behavioral targeting. It also seems to put developers on a bit of a pedestal (Python > Cooking) which I don't really like. I think critiques are good but we need to be very precise about what we're critiquing. If we're being critical of behavioral and programmatic advertising, let's link to the NYT article about when they removed most of it and revenue stayed the same.

2021-03-05 22:52 UTC, davidfischer commented on content/posts/ad-tracking-is-reputation-arbitrage.md
> +Title: Ad Retargeting is Hurting Open Source Publisher & Helping Bad Recipe Sites
```suggestion
Title: Ad Retargeting is Hurting Open Source Publishers & Helping Bad Recipe Sites
```

I don't like the messaging here much. It seems to say Python is higher value than Recipes which while it might be true probably isn't the message we want to send. I know we talk about recipe sites in the post but I'd like to change it to just a "low value publisher" or something like that.

2021-03-05 22:52 UTC, davidfischer commented on content/posts/ad-tracking-is-reputation-arbitrage.md
> +> **Ad retargeting** is a technology that uses cookies and other invasive targeting methods to follow your users across multiple websites.
```suggestion
> **Ad retargeting** is a technology that uses cookies and other invasive targeting methods to target users with ads who have taken specific actions in the past like visit certain websites, browsed certain products, or watched specific videos.
```

I think being really precise here helps our credibility.

2021-03-05 22:52 UTC, davidfischer commented on content/posts/ad-tracking-is-reputation-arbitrage.md
> +**Retargeting is valuable because it allows advertisers to show ads to your audience on cheaper sites.**
This example above is more a critique of behavioral targeting -- learning about the user and showing ads based on their features -- than retargeting specifically. Retargeting is usually used by sellers on websites in combination with ad networks. The most common way it's used is like this:

- I'm a company and I sell product X
- I put a pixel on my website for ad networks A, B, and C
- I can now target product X ads on networks A, B, and C to folks who have visited my website in the past.

2021-03-05 22:52 UTC, davidfischer commented on content/posts/ad-tracking-is-reputation-arbitrage.md
> +* Advertisers want to pay more to reach "Python developers" than "people who cook"
Is this the story we want to tell? It feels almost classist.

2021-03-05 22:52 UTC, davidfischer commented on content/posts/ad-tracking-is-reputation-arbitrage.md
> +If you want to learn more, we highly recommend reading the [EFF blog](https://www.eff.org/).*
This feels like a throwaway.

2021-03-05 22:58 UTC, davidfischer commented on content/posts/ad-tracking-is-reputation-arbitrage.md
> +**Retargeting is valuable because it allows advertisers to show ads to your audience on cheaper sites.**
Now tracking users does hurt high quality publishers and does help low quality publishers so that is correct. However, the way that works is only sort of related to retargeting and not in the traditional sense.

2021-03-08 15:05 UTC, ericholscher commented
@davidfischer yea, I was just trying to make it click-baitey, but maybe the answer is just a sober explanation about what is wrong w/ tracking without the recipe site silliness?

2021-05-20 21:29 UTC, ericholscher commented
Replaced by #150

2021-05-20 21:29 UTC, closed without merging